// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AppMusicaSedas.Models;
//
//    var cancion = Cancion.FromJson(jsonString);

namespace AppMusicaSedas.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Cancion
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("nombre_cancion")]
        public string NombreCancion { get; set; }

        [JsonProperty("artista")]
        public string Artista { get; set; }

        [JsonProperty("album")]
        public string Album { get; set; }

        [JsonProperty("urlCancion")]
        public Uri UrlCancion { get; set; }

        [JsonProperty("urlImagen")]
        public Uri UrlImagen { get; set; }

        [JsonProperty("genero")]
        public string Genero { get; set; }
    }

    public partial class Cancion
    {
        public static List<Cancion> FromJson(string json) => JsonConvert.DeserializeObject<List<Cancion>>(json, AppMusicaSedas.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Cancion> self) => JsonConvert.SerializeObject(self, AppMusicaSedas.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
